### ISSUE TITLE
msgpack error (packet must be a buffer)

### ISSUE THREAD

**Issue by AgarioCheats** [davidmann4/ogar-feeder-bot#1]
I get this error when trying to run node feeder.js

feeder.js:198
            var packet = msgpack.unpack(buffer);
                                 ^
TypeError: First argument must be a Buffer

**Comment by davidmann4** [comment]
Do you have a map server running?

**Comment by davidmann4** [comment]
Also you need to create a config.js ( copy config.sample.js)

**Comment by AgarioCheats** [comment]
Yes map server is running, and config is created.
socks.txt is empty -> but it shouldn't interfre?

**Comment by clouedoc** [comment]
map server is running on the same port of the config.sample.js ?

**Comment by davidmann4** [comment]
working for you @camilleeyries ?

**Comment by clouedoc** [comment]
I am french... sorry I don't understand.

**Comment by clouedoc** [comment]
I want help you to make this bot :D

**Comment by davidmann4** [comment]
is the programm working for you at the moment?

**Comment by clouedoc** [comment]
I have not tried it yet

**Comment by davidmann4** [comment]
@AgarioCheats which version of msgpack do you use?
npm install msgpack

**Comment by clouedoc** [comment]
@davidmann4 what is the script for the minimap ?

**Comment by AgarioCheats** [comment]
Map server is running on the same server. port 34343
server is running on port 420
config.js and feeder.js are in the /examples folder. I changed this to point to the ../ folder

var AgarioClient = require('../agario-client.js');  
other than that, no changes.
console -> node feeder.js and the error comes up

**Comment by clouedoc** [comment]
May be type in console.log(type buffer);

**Comment by AgarioCheats** [comment]
node feeder.js
http://
Requesting party server
error on startup
ws://127.0.0.1:34343 connected

/root/agario-client-master/examples/feeder.js:198
            var packet = msgpack.unpack(buffer);
                                 ^
TypeError: First argument must be a Buffer
    at WebSocket.ws.onmessage (/root/agario-client-master/examples/feeder.js:198:34)
    at WebSocket.onMessage (/root/agario-client-master/node_modules/ws/lib/WebSocket.js:414:14)
    at WebSocket.emit (events.js:98:17)
    at Receiver.onbinary (/root/agario-client-master/node_modules/ws/lib/WebSocket.js:804:10)
    at /root/agario-client-master/node_modules/ws/lib/Receiver.js:533:18
    at /root/agario-client-master/node_modules/ws/lib/Receiver.js:357:7
    at /root/agario-client-master/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:278:3)
    at onwrite (_stream_writable.js:270:7)

**Comment by clouedoc** [comment]
error on startup...

**Comment by clouedoc** [comment]
Requesting party server ?

**Comment by davidmann4** [comment]
which version of the server do you use?

**Comment by davidmann4** [comment]
also more debug output would be neat:

console.log(buffer);

**Comment by AgarioCheats** [comment]
version of minimap server? The newest one

**Comment by davidmann4** [comment]
git clone ?

**Comment by AgarioCheats** [comment]
no, downloaded the v0.46

**Comment by davidmann4** [comment]
what does the console from the map server write?

use git clone

**Comment by AgarioCheats** [comment]
minimap says:

mini-map-server@0.0.1 start /root/agar-mini-map-0.46/server

> node dist/server.js

server is now on the port:34343

running feeder------------------

node feeder.js
http://
Requesting party server
error on startup
ws://127.0.0.1:34343 connected
{ '0': 130,
  '1': 164,
  '2': 116,
  '3': 121,
  '4': 112,
  '5': 101,
  '6': 204,
  '7': 129,
  '8': 164,
  '9': 100,
  '10': 97,
  '11': 116,
  '12': 97,
  '13': 146,
  '14': 131,
  '15': 164,
  '16': 110,
  '17': 97,
  '18': 109,
  '19': 101,
  '20': 144,
  '21': 162,
  '22': 110,
  '23': 111,
  '24': 0,
  '25': 163,
  '26': 105,
  '27': 100,
  '28': 115,
  '29': 220,
  '30': 0,
  '31': 25,
  '32': 205,
  '33': 203,
  '34': 60,
  '35': 205,
  '36': 205,
  '37': 170,
  '38': 205,
  '39': 205,
  '40': 171,
  '41': 205,
  '42': 205,
  '43': 172,
  '44': 205,
  '45': 205,
  '46': 173,
  '47': 205,
  '48': 205,
  '49': 174,
  '50': 205,
  '51': 205,
  '52': 175,
  '53': 205,
  '54': 205,
  '55': 176,
  '56': 205,
  '57': 205,
  '58': 177,
  '59': 205,
  '60': 205,
  '61': 178,
  '62': 205,
  '63': 205,
  '64': 179,
  '65': 205,
  '66': 205,
  '67': 180,
  '68': 205,
  '69': 205,
  '70': 181,
  '71': 205,
  '72': 205,
  '73': 182,
  '74': 205,
  '75': 205,
  '76': 183,
  '77': 205,
  '78': 205,
  '79': 184,
  '80': 205,
  '81': 226,
  '82': 18,
  '83': 205,
  '84': 226,
  '85': 105,
  '86': 205,
  '87': 226,
  '88': 149,
  '89': 205,
  '90': 226,
  '91': 150,
  '92': 205,
  '93': 226,
  '94': 214,
  '95': 205,
  '96': 226,
  '97': 215,
  '98': 205,
  '99': 226,
  '100': 216,
  '101': 205,
  '102': 226,
  '103': 217,
  '104': 205,
  '105': 228,
  '106': 165,
  '107': 131,
  '108': 164,
  '109': 110,
  '110': 97,
  '111': 109,
  '112': 101,
  '113': 144,
  '114': 162,
  '115': 110,
  '116': 111,
  '117': 1,
  '118': 163,
  '119': 105,
  '120': 100,
  '121': 115,
  '122': 144,
  BYTES_PER_ELEMENT: 1,
  get: [Function: get],
  set: [Function: set],
  slice: [Function: slice],
  subarray: [Function: subarray],
  buffer:
   { '0': 130,
     '1': 164,
     '2': 116,
     '3': 121,
     '4': 112,
     '5': 101,
     '6': 204,
     '7': 129,
     '8': 164,
     '9': 100,
     '10': 97,
     '11': 116,
     '12': 97,
     '13': 146,
     '14': 131,
     '15': 164,
     '16': 110,
     '17': 97,
     '18': 109,
     '19': 101,
     '20': 144,
     '21': 162,
     '22': 110,
     '23': 111,
     '24': 0,
     '25': 163,
     '26': 105,
     '27': 100,
     '28': 115,
     '29': 220,
     '30': 0,
     '31': 25,
     '32': 205,
     '33': 203,
     '34': 60,
     '35': 205,
     '36': 205,
     '37': 170,
     '38': 205,
     '39': 205,
     '40': 171,
     '41': 205,
     '42': 205,
     '43': 172,
     '44': 205,
     '45': 205,
     '46': 173,
     '47': 205,
     '48': 205,
     '49': 174,
     '50': 205,
     '51': 205,
     '52': 175,
     '53': 205,
     '54': 205,
     '55': 176,
     '56': 205,
     '57': 205,
     '58': 177,
     '59': 205,
     '60': 205,
     '61': 178,
     '62': 205,
     '63': 205,
     '64': 179,
     '65': 205,
     '66': 205,
     '67': 180,
     '68': 205,
     '69': 205,
     '70': 181,
     '71': 205,
     '72': 205,
     '73': 182,
     '74': 205,
     '75': 205,
     '76': 183,
     '77': 205,
     '78': 205,
     '79': 184,
     '80': 205,
     '81': 226,
     '82': 18,
     '83': 205,
     '84': 226,
     '85': 105,
     '86': 205,
     '87': 226,
     '88': 149,
     '89': 205,
     '90': 226,
     '91': 150,
     '92': 205,
     '93': 226,
     '94': 214,
     '95': 205,
     '96': 226,
     '97': 215,
     '98': 205,
     '99': 226,
     '100': 216,
     '101': 205,
     '102': 226,
     '103': 217,
     '104': 205,
     '105': 228,
     '106': 165,
     '107': 131,
     '108': 164,
     '109': 110,
     '110': 97,
     '111': 109,
     '112': 101,
     '113': 144,
     '114': 162,
     '115': 110,
     '116': 111,
     '117': 1,
     '118': 163,
     '119': 105,
     '120': 100,
     '121': 115,
     '122': 144,
     slice: [Function: slice],
     byteLength: 123 },
  length: 123,
  byteOffset: 0,
  byteLength: 123 }

/root/agario-client-master/examples/feeder.js:199
            var packet = msgpack.unpack(buffer);

**Comment by AgarioCheats** [comment]
Using this version: https://github.com/dimotsai/agar-mini-map/archive/v0.46.zip

**Comment by davidmann4** [comment]
can you sue the git clone version ?

**Comment by AgarioCheats** [comment]
I'll try, which version do i choose? wget -o agar-minimap.zip https://github.com/____Version?

**Comment by davidmann4** [comment]
git clone https://github.com/dimotsai/agar-mini-map.git
cd agar-mini-map/server
npm install && npm run build

then just do 

npm run start

**Comment by AgarioCheats** [comment]
Same with the new one. The minimap logs: 
player 1 127.0.0.1:59025 joined.
player 1 127.0.0.1:59025 has left.

and the node.js feeder logs:

```
var packet = msgpack.unpack(buffer);
                             ^
```

TypeError: First argument must be a Buffer

**Comment by davidmann4** [comment]
hmm wtf - node version? msgpack version?

**Comment by AgarioCheats** [comment]
node --version
v0.10.41

How do i find the msgpack version?

Server is running Centos

**Comment by davidmann4** [comment]
node --version
v0.12.2
 on my side

**Comment by AgarioCheats** [comment]
Centos?

**Comment by davidmann4** [comment]
debian

**Comment by davidmann4** [comment]
to get things right: 

you did the following:

git clone https://github.com/davidmann4/agario-feeder-bot.git
cd agario-feeder-bot
**create config.js**
node feeder.js

**Comment by AgarioCheats** [comment]
Im trying to run it on an ubuntu server now, though i can't get the map server to run on it. So i'll try to run map server on centos, however i updated  node version on centos to node v5.4.0 and now i can't run the map server with it. (error return process.dlopen(module, path._makeLong(filename));
                 )

Do you know how i can downgrade node, or use the previous version?

yum install https://nodejs.org/en/blog/release/v0.12.2/ ?

**Comment by davidmann4** [comment]
just use the newest node version ...

**Comment by AgarioCheats** [comment]
Newest node version doesn't work (v5.4.0) with the minimap

Okay downgraded to node version v0.10.30
minimap works now

**Comment by davidmann4** [comment]
i use v0.12.2 and everything works :)

**Comment by AgarioCheats** [comment]
Allright it's finally not displaying the error anymore! 
Using the agar-map on centos, and feeder.js on ubuntu
But now, I can't see the cell ingame. feeder.js only logs 
Requesting party server
error on startup
 ws://ip:34343 connected
and nothing else

**Comment by davidmann4** [comment]
how do oyu launch the script? do you have a proxy loaded ?

**Comment by AgarioCheats** [comment]
No proxies loaded, socks.txt is empty
Wrote in console: 
node feeder.js

---

  }catch(e){
        console.log('error on startup');

## I get the error on startup. 

```
    AgarioClient.servers.getPartyServer({region: 'EU-London', party_key: key, agent: agent}, function(srv) {
```

I think perhaps its this code?

And if proxies/socks  (socks5?)are needed, what format do i enter them in socks.txt?
127.0.0.1:ip?

**Comment by davidmann4** [comment]
it requires proxies atm also you have to pass a room id 
node feeder.js GS3L9

**Comment by davidmann4** [comment]
will push a update which allows no proxy aswell

**Comment by davidmann4** [comment]
just change  agent = HttpsProxyAgent(opts); to  agent = null; (line 279(

have to leave - sorry

**Comment by AgarioCheats** [comment]
Okay, thanks a lot. I will try.

**Comment by davidmann4** [comment]
did you managed to run it?

**Comment by AgarioCheats** [comment]
Still trying, perhaps something with the proxy?
Tried looking for one, but maybe it's not working. Where do i find a working proxy?

**Comment by davidmann4** [comment]
with dccb7e364c19376f07aa78ce3488e9ac73a0d8a2 @camilleeyries  added the support of not using proxies.

**Comment by davidmann4** [comment]
just do 
git pull

**Comment by davidmann4** [comment]
if you write NOPROXY in your socks.txt you will use your local ip

**Comment by AgarioCheats** [comment]
Awesome! Noproxy worked!!
They follow the cell only though, does agar-minimap fetch mouse coords?
Would it be possible to send keyboard input? 
I imagine agar-minimap doesn't have the ability to fetch "e" from the keyboard, for example. So perhaps adding it to the agar-minimap extension via tampermonkey, i'd imagine someting like
case (press e) {
send to server E button down
}

on server
case (e pressed) {
bot.cells.split
}

**Comment by davidmann4** [comment]
please open a new issue for feature requests.

/closed
