### ISSUE TITLE
Help, when I connect I get the error "unexpected server response (403)"

### ISSUE THREAD

**Issue by loboere** [davidmann4/ogar-feeder-bot#110]
When I start the bot and join a game everything seems to work. But then I see the following Error Msgs on the console:

Connection Failed: Error: unexpected server response (403)
Bot_37: Connection Failed: Error: unexpected server response (403)
Bot_44: Connection Failed: Error: unexpected server response (403)
Bot_40: Connection Failed: Error: unexpected server response (403)
Bot_31: Connecting to: ws://127.0.0.1:443
Bot_31: Connection Failed: Error: unexpected server response (403)
Bot_32: Connecting to: ws://127.0.0.1:443

**Comment by auxo-git** [comment]
The proxies your using are most likely banned or just don't work..
This is like 98% of public proxies

**Comment by davidmann4** [comment]
@auxo-git is right, you need stable proxies to connect to a server. In your case connecting through a proxy to 127.0.0.1 could be problematic aswell.

**Comment by mhchen-UA** [comment]
Just search free http proxies and keep testing them until one of them works.

**Comment by hyuga01** [comment]
when i type the command: node feeder.js i get message like 
"Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/agario-feeder-bot-master/feeder.js:418:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)"

**Comment by davidmann4** [comment]
npm install ws

**Comment by akaashjain1** [comment]
@davidmann4  what proxies should we use. please help us!

**Comment by davidmann4** [comment]
http btw https

**Comment by hyuga01** [comment]
thank you the previous error does not show up now.
and the bots work aswell but for only few seconds. then they stop. Giving me this new error statement.
"/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode
    at WebSocket.onError (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onerror (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/Receiver.js:212:12)
    at Receiver.add (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)"

**Comment by davidmann4** [comment]
please open a separate issue

**Comment by branb1206** [comment]
help this is what i get when i open the start bots
Bot_79: Connecting to: ws://23.239.18.218:443
Bot_1: Connection Success, spawning
Bot_1: [warning] unknown packet ID(18): 12
Bot_1: [warning] unknown packet ID(18): 12
Bot_1: New Cell Generated (1083746859)
C:\Users\ben\Desktop\FreeAgarBots v2.5\feeder.js:406
                if(valid_player_pos["suicide_targets"] == null){
                                   ^

TypeError: Cannot read property 'suicide_targets' of null
    at Object.FeederBot.getCandidateBall (C:\Users\ben\Desktop\FreeAgarBots v2.5
\feeder.js:406:36)
    at Object.FeederBot.recalculateTarget (C:\Users\ben\Desktop\FreeAgarBots v2.
5\feeder.js:485:34)
    at null._repeat (C:\Users\ben\Desktop\FreeAgarBots v2.5\feeder.js:91:21)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

C:\Users\ben\Desktop\FreeAgarBots v2.5>pause
Press any key to continue . . .
