### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by salahxbox** [davidmann4/ogar-feeder-bot#111]
Your environment has been set up for using Node.js 4.2.6 (ia32) and npm.

C:\Users\salah>git clone https://github.com/davidmann4/agario-feeder-bot
Cloning into 'agario-feeder-bot'...
remote: Counting objects: 369, done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 369 (delta 44), reused 0 (delta 0), pack-reused 284Receiving objects:  85% (314/369), 52.01 KiB | 84.00 KiReceiving objects: 100% (369/369), 68.68 KiB | 84.00 KiB/s, done.

Resolving deltas: 100% (209/209), done.
Checking connectivity... done.

C:\Users\salah>npm install package.json
package.json@0.0.0 node_modules\package.json

C:\Users\salah>npm install libs
libs@0.1.2 node_modules\libs
└── dateformat@1.0.2-1.2.3

C:\Users\salah>node feeder.js
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Users\salah\feeder.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

C:\Users\salah>

---

how to run feeder.js in nodejd comand prompt
did i done something wrong in the command above please help and thx
i have updated the whole script

**Comment by auxo-git** [comment]
Try to put it in a empty folder

**Comment by davidmann4** [comment]
wow that is interessting, is it already working? what was the solution?

**Comment by davidmann4** [comment]
tutorial video: https://www.youtube.com/watch?v=FVNNo93ZVGg

**Comment by salahxbox** [comment]
thank you so much david
now this the new issue
C:\DATA\agario-feeder-bot-master>node feeder.js
agario-feeder-bot started! Join a game in Chrome with the Userscript installed.
Press CTRL + C to stop this script.
startup
server-booted-up

---

this is what i get i have followed all steps in your video

**Comment by davidmann4** [comment]
so whats the problem with that? install the userscript like in the video and join a game

**Comment by mhchen-UA** [comment]
make sure that in your Proxy.txt you have working proxies. Davidmann put his own proxies in, I think he might've paid for some. I just searched free  http proxies online and tested to see which one works.  

You can tell that it's working when the command prompt starts saying stuff like "bot_1 spawning" "The leaderboard is ..." etc.

Also since agario made it that 3 "clients" connect per ip address, each proxy you have can only give you 3 bots probably.
