### ISSUE TITLE
Bots work for some time then they stop working.

### ISSUE THREAD

**Issue by hyuga01** [davidmann4/ogar-feeder-bot#123]
the bots work for only few seconds. then they stop. Giving me this new error statement.
"/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:426
event.type = 'error';
^

TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode
at WebSocket.onError (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:426:16)
at emitTwo (events.js:100:13)
at WebSocket.emit (events.js:185:7)
at Receiver.onerror (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:851:10)
at Receiver.error (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/Receiver.js:321:8)
at Receiver.processPacket (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/Receiver.js:212:12)
at Receiver.add (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/Receiver.js:95:24)
at Socket.realHandler (/Users/qasimhamza/agardata/agario/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:800:20)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)"

**Comment by DanielLewis97NL** [comment]
https://github.com/websockets/ws/issues/669

It's a problem is with WS itself, the fix is there ^

**Comment by makandz** [comment]
@davidmann4 Old post!

**Comment by DanielLewis97NL** [comment]
@MastaCoder indeed, this is a confirmed error with ws and does not belong here.

**Comment by davidmann4** [comment]
Jup problem with ws i hope they fix it soon

**Comment by ghost** [comment]
just go to DATA> ogar-feeder-bot>node_modules> ws>lib>WebSocket.js then go to line 426 and 427 and comment it that should fix it
