### ISSUE TITLE
RangeError: index out of range

### ISSUE THREAD

**Issue by aleksiaaa** [davidmann4/ogar-feeder-bot#131]
Getting this error after 20 seconds of playing.

RangeError: index out of range
    at checkOffset (buffer.js:644:11)
    at Buffer.readUInt32LE (buffer.js:706:5)
    at Object.Packet.readUInt32LE (/Users/aleksiaaltonen/Desktop/agario-feeder-bot-master/node_modules/agario-client/packet.js:77:29)
    at Client.processors.16 (/Users/aleksiaaltonen/Desktop/agario-feeder-bot-master/node_modules/agario-client/agario-client.js:224:39)
    at Object.Client.onMessage (/Users/aleksiaaltonen/Desktop/agario-feeder-bot-master/node_modules/agario-client/agario-client.js:148:13)
    at WebSocket.onMessage (/Users/aleksiaaltonen/Desktop/agario-feeder-bot-master/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (/Users/aleksiaaltonen/Desktop/agario-feeder-bot-master/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:823:10)
    at /Users/aleksiaaltonen/Desktop/agario-feeder-bot-master/node_modules/agario-client/node_modules/ws/lib/Receiver.js:537:18

**Comment by brentco** [comment]
What worked for me is adding `crash = false;` to 

```
    onPacketError: function(packet, err) {
    var crash = true;

    this.emit('packetError', packet, err, function() {
        crash = false;
    });

    //to prevent crashing
    crash = false;

    if(crash) {
        if(this.debug >= 1)
            this.log('Packet error detected! Check packetError event in README.md');
        throw err;
    }
},` 
```

in agario-client.js and adding `try {} catch(e) {}` to:
`
        function onError (event) {

```
try {

event.type = 'error';

event.target = target;

listener.call(target, event);

} catch(e) {}
    }`
```

in WebSocket.js

After an hour, such events have occured but the bots never crashed. The "error" is delegated to be an unknown packet instead. Sorry for the messy code, I can't seem to get the markdown to properly wrap the code.

**Comment by davidmann4** [comment]
You should tell this the agario-client guys so they can fix it

**Comment by davidmann4** [comment]
fixed in newest version
