### ISSUE TITLE
 get this error. any solution

### ISSUE THREAD

**Issue by akaashjain1** [davidmann4/ogar-feeder-bot#139]
C:\DATA\agario-feeder-bot-master>node feeder.js
module.js:328
    throw err;
    ^

Error: Cannot find module 'socks'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\DATA\agario-feeder-bot-master\feeder.js:469:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

C:\DATA\agario-feeder-bot-master>

**Comment by DanielLewis97NL** [comment]
in cmd:

cd c:\DATA
npm install socks
