### ISSUE TITLE
Another Crash!

### ISSUE THREAD

**Issue by mbm3** [davidmann4/ogar-feeder-bot#156]
So the crashes I had before ( #152 ) were fixed.  But now I get this every so often.

/root/MEGA/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of no handler for opcode 15
    at WebSocket.onError (/root/MEGA/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onerror (/root/MEGA/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/root/MEGA/node_modules/agario-client/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/root/MEGA/node_modules/agario-client/node_modules/ws/lib/Receiver.js:234:43)
    at Receiver.add (/root/MEGA/node_modules/agario-client/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/root/MEGA/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)

**Comment by WJKH** [comment]
I'm using node v0.12.9 (I'm using minimap too) and never an issue.
Try it and lets see if you have the same issue.

**Comment by mbm3** [comment]
@WJKH link to that version? (p.s. im using latest version of agario-feeder-bot)

**Comment by WJKH** [comment]
I'm not using last feeder version, I'll update soon and test it too.
Try it https://nodejs.org/download/release/v0.12.9/

**Comment by mbm3** [comment]
lol just comment out the lines the error occur on, it works!
