### ISSUE TITLE
RangeError: index out of range  (Please answer me fast thanks :)

### ISSUE THREAD

**Issue by DarkSaTla** [davidmann4/ogar-feeder-bot#170]
hey,
when i started the bots in 5 - 10 min i get this crash message:
`C:\Users\agario\node_modules\agario-client\agario-client.js:166
            throw err;
            ^

RangeError: index out of range
    at checkOffset (buffer.js:635:11)
    at Buffer.readUInt32LE (buffer.js:697:5)
    at Object.Packet.readUInt32LE (C:\Users\agario\node_modules\agario-client\pa
cket.js:77:29)
    at Client.processors.16 (C:\Users\agario\node_modules\agario-client\agario-c
lient.js:306:34)
    at Object.Client.onMessage (C:\Users\agario\node_modules\agario-client\agari
o-client.js:148:13)
    at WebSocket.onMessage (C:\Users\agario\node_modules\ws\lib\WebSocket.js:418
:14)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onbinary (C:\Users\agario\node_modules\ws\lib\WebSocket.js:823:1
0)
    at C:\Users\agario\node_modules\ws\lib\Receiver.js:537:18`

what i need to do to fix it? please answer me
thanks! :)

**Comment by pantshobhit** [comment]
Hii, changing the maxbots limit from 128 to something higher in config.js worked for me. Also, you will get more bots and the rate of bots will keep on increasing but after a time you will start experiencing lag and eventually a blank screen, so, I will recommend changing the value to something not more than 300 and reentering node feeder.js everytime you get this error.

**Comment by DarkSaTla** [comment]
didnt work :(

**Comment by makandz** [comment]
How many proxies do you have?

**Comment by sejo153** [comment]
I have the same problem. Its myb because a lot of proxies?

**Comment by davidmann4** [comment]
it is a problem with agario-client

**Comment by davidmann4** [comment]
should be fixed with newest patch
