### ISSUE TITLE
CRASH: event.type = 'error'; (ws lib bug)

### ISSUE THREAD

**Issue by Nick8fr32** [davidmann4/ogar-feeder-bot#174]
ADMIN EDIT: to fix install https://github.com/websockets/ws/pull/681

== original msg ==
C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of reserved fields must be empty
    at WebSocket.onError (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426:16)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onerror (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\Receiver.js:195:12)
    at Receiver.add (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)

**Comment by gcsoftware** [comment]
Temporary fix is to open WebSocket.js and comment out the 3 lines inside onError. Line 426

**Comment by Nick8fr32** [comment]
what do u mean with comment out @gcsoftware

**Comment by gcsoftware** [comment]
@Nick8fr32 It should look like this:
function onError (event) {
    //event.type = 'error';
    //event.target = target;
    //listener.call(target, event);
  }

**Comment by Nick8fr32** [comment]
still dosent work @gcsoftware

**Comment by gcsoftware** [comment]
@Nick8fr32 Same error or different?

**Comment by Nick8fr32** [comment]
i think it is the same 

C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode
    at WebSocket.onError (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426:16)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onerror (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\Receiver.js:212:12)
    at Receiver.add (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)  

@gcsoftware

**Comment by gcsoftware** [comment]
@Nick8fr32 Make sure to apply that fix to both of them. There should be one located at C:\Users\Nicklas\Desktop\test bots v2\node_modules\agario-client\node_modules\ws\lib\WebSocket.js:426

and another at C:\Users\Nicklas\Desktop\test bots v2\node_modules\ws\lib\WebSocket.js:426

**Comment by Nick8fr32** [comment]
i have done and still dont work @gcsoftware

**Comment by Nick8fr32** [comment]
can u send me yours websocket file @gcsoftware

**Comment by agarioBotDev** [comment]
@gcsoftware your solution is shit (sry), you can not fix an error by ingnoring them. DO:
`bot.client.on('packetError', function (packet, err, preventCrash) {
            bot.log('Packet error detected for packet: ' + packet.toString());
            bot.log('Crash will be prevented, bot will be disconnected');
            preventCrash();
            bot.client.disconnect();


        });`

**Comment by agarioBotDev** [comment]
@gcsoftware you cannot fix an error by ingnoring it, DO:

``` javascript
bot.client.on('packetError', function (packet, err, preventCrash) {
            bot.log('Packet error detected for packet: ' + packet.toString());
            bot.log('Crash will be prevented, bot will be disconnected');
            preventCrash();
            bot.client.disconnect();
});
```

**Comment by ravyn120** [comment]
@agarioBotDev make a code so when it disconnects from packet errors it reconnects the bots

**Comment by gcsoftware** [comment]
@agarioBotDev I never stated it would perm fix anything. I said temporary for a reason.

**Comment by davidmann4** [comment]
https://github.com/websockets/ws/pull/681 is a fix for this problem
