### ISSUE TITLE
Blind Mode: collect food until you see the Player cell and run into it

### ISSUE THREAD

**Issue by davidmann4** [davidmann4/ogar-feeder-bot#199]
- add the mode to config.js
- add the new behavior to the feeder.js
- emit a packet when the player gets new balls
- add the logic to run to the player into feeder.js
- distribute the player ball ids via the server

**Comment by davidmann4** [comment]
done - you can enable the mode in config.js

**Comment by WJKH** [comment]
I'm getting too many packet error.

```
Bot_22: Packet error detected for packet: 40 ca ed 96 6d 92 10 b6 c0 a3 62 bd aa c9 7a 9d 40 60 8d 44 9a 64 db 5b 40 a9 58 af 6a b2 06 b4 40
Bot_22: Crash will be prevented, bot will be disconnected
Bot_14: Packet error detected for packet: 40 fe a9 13 a5 d7 ed ae c0 d4 74 96 8c 57 1c b4 c0 04 ac d8 b5 50 24 9c 40 52 d3 59 32 5e d1 9d c0
Bot_14: Crash will be prevented, bot will be disconnected
Bot_53: Packet error detected for packet: 40 f7 19 85 ab ba 33 a2 40 0c ba 0b 48 22 d0 c0 c0 56 a7 36 25 f6 a0 b9 40 17 74 17 90 44 f8 b4 c0
Bot_53: Crash will be prevented, bot will be disconnected
Bot_28: Packet error detected for packet: 40 67 9c d5 34 85 2d b4 c0 00 00 00 00 80 f3 c1 c0 00 00 00 00 00 0a a1 c0 00 00 00 00 00 3f b7 c0
Bot_28: Crash will be prevented, bot will be disconnected
Bot_56: Packet error detected for packet: 40 00 00 00 00 00 7a a2 40 00 00 00 00 00 6e a7 c0 00 00 00 00 00 bd bf 40 00 00 00 00 00 20 6e 40
Bot_56: Crash will be prevented, bot will be disconnected
Bot_47: Packet error detected for packet: 40 ee ec c5 7b 75 ce af c0 54 d1 9b 01 2b d4 ae c0 24 26 74 08 15 63 9a 40 50 45 6f 06 ac 10 86 c0
Bot_47: Crash will be prevented, bot will be disconnected
Bot_16: Packet error detected for packet: 40 1b 91 e9 72 53 95 b0 c0 a6 05 02 d6 f9 67 b3 40 00 fa 07 c5 ce 32 89 40 d3 02 01 eb fc 07 c0 40
Bot_16: Crash will be prevented, bot will be disconnected
Bot_20: Packet error detected for packet: 40 c8 05 ae 32 52 40 b3 40 33 73 c6 f8 32 dd 96 40 e4 02 57 19 29 e0 c4 40 cd 9c 31 be 4c 5f b2 40
Bot_20: Crash will be prevented, bot will be disconnected
Bot_10: Packet error detected for packet: 40 6d 91 19 1d 2a 80 c5 c0 ef 5b ad ce 58 9a ae 40 3e c3 85 82 51 e0 b9 c0 d2 ed d5 54 51 3d b6 40
Bot_10: Crash will be prevented, bot will be disconnected
Bot_23: Packet error detected for packet: 40 ee de b2 2f bb 5a bb c0 84 8e 5f 53 3f cc c4 c0 b9 7b cb be ec 6a 93 c0 08 1d bf a6 7e f0 bc c0
Bot_23: Crash will be prevented, bot will be disconnected
Bot_52: Packet error detected for packet: 40 00 00 00 00 00 01 c3 c0 00 00 00 00 00 d8 b9 c0 00 00 00 00 00 04 af c0 00 00 00 00 00 60 aa c0
Bot_52: Crash will be prevented, bot will be disconnected
Bot_18: Packet error detected for packet: 40 7f f1 60 da 87 1a be c0 27 29 c1 10 27 72 92 c0 fc c5 83 69 1f 6a 9e c0 6d 6b 9f 77 ec 16 a0 40
Bot_18: Crash will be prevented, bot will be disconnected
```

Commented line 189, preventCrash(); to see what happen and...

```
Bot_1: Connection Success, spawning
Bot_1: Packet error detected for packet: 40 c6 ab 97 05 d1 a5 c1 c0 d8 58 08 92 d5 06 ad c0 73 49 0d ad 80 f2 b3 40 4a 3a 9c f7 5b 5d c4 40 08 00 00 00 31 00 2e 00 33 00 2e 00 39 00 00 00
Bot_1: Crash will be prevented, bot will be disconnected
/home/afeeder/AFB/F1/node_modules/agario-client/agario-client.js:172
            throw err;
                  ^
ReferenceError: map_max_x is not defined
    at Object.<anonymous> (/home/afeeder/AFB/F1/feeder.js:111:36)
    at Object.emit (events.js:118:17)
    at Client.processors.64 (/home/afeeder/AFB/F1/node_modules/agario-client/agario-client.js:436:20)
    at Object.Client.onMessage (/home/afeeder/AFB/F1/node_modules/agario-client/agario-client.js:154:13)
    at WebSocket.onMessage (/home/afeeder/AFB/F1/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (/home/afeeder/AFB/F1/node_modules/ws/lib/WebSocket.js:823:10)
    at /home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:537:18
    at Receiver.applyExtensions (/home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:364:5)
    at /home/afeeder/AFB/F1/node_modules/ws/lib/Receiver.js:531:14
```

**Comment by WJKH** [comment]
BTW.. I have some bots coming @davidmann4 :+1:
