### ISSUE TITLE
getCandidateBall error?

### ISSUE THREAD

**Issue by easyrider81** [davidmann4/ogar-feeder-bot#203]
E:\DATA\ogar-feeder-bot-master\feeder.js:452
            bot.candidate_ball = getCandidateBall(bot);
                                 ^

ReferenceError: getCandidateBall is not defined
    at Object.FeederBot.recalculateTarget (E:\DATA\ogar-feeder-bot-master\feeder.js:452:34)
    at null._repeat (E:\DATA\ogar-feeder-bot-master\feeder.js:91:21)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by davidmann4** [comment]
ohh good finding let me push an update

**Comment by davidmann4** [comment]
pushed & fixed

**Comment by easyrider81** [comment]
thanks i'll give it a go now
