### ISSUE TITLE
!!UPDATE USERSCRIPT!!

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#209]
hello there isd a problem where when i try to connect my bots to my private server it doesn't spawn any bots and tells me !!UPDATE USERSCRIPT!! although i already updated it, it still wont do anything

**Comment by davidmann4** [comment]
hmm funny - which one are you using ?

**Comment by ghost** [comment]
im using the one thats on ogar-feeder-bot.user.js

**Comment by ghost** [comment]
and this error:
TypeError: Cannot assign to read only property 'type' of no handler for opcode 7
    at WebSocket.onError (C:\DATA\ogar-feeder-bot-master\node_modules\ws\lib\WebSocket.js:426:16)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onerror (C:\DATA\ogar-feeder-bot-master\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (C:\DATA\ogar-feeder-bot-master\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (C:\DATA\ogar-feeder-bot-master\node_modules\ws\lib\Receiver.js:234:43)
    at Receiver.add (C:\DATA\ogar-feeder-bot-master\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (C:\DATA\ogar-feeder-bot-master\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)

**Comment by mbm3** [comment]
@Butterflypanda  comment out line 426 of WebSocket.js

**Comment by ghost** [comment]
thx alot :)

**Comment by ghost** [comment]
thank you

**Comment by davidmann4** [comment]
works again? good
