### ISSUE TITLE
Strange error. Any way to fix this ?

### ISSUE THREAD

**Issue by picusc** [davidmann4/ogar-feeder-bot#226]
Bot_131: Packet error detected for packet: 10 00 00 69 46 10 00 53 f0 ff ff 9d 14 00 00 4d 00 a5 07 ff 00 00 00 02 4e 10 00 e7 ef ff ff 8d 13 00 00 2d 00 a5 07 ff 00 00 00 7f 4e 10 00 a9 ef ff ff 34 13 00 00 3e 00 a5 07 ff 00 00 00 f8 f8 4e 10 00 00 f6 ff ff 95 15 00 00 46 00 07 96 ff 00 00 00 34 51 10 00 da f5 ff ff 44 12 00 00 21 00 ed ff 07 00 00 00 00 00 00 00 00 00 00

C:\Users...\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode
    at WebSocket.onError (C:\Users...\node_modules\ws\lib\WebSocket.js:426:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (C:\Users...\node_modules\ws\lib\WebSocket.js:851:10)
    at Receiver.error (C:\Users...\node_modules\ws\lib\Receiver.js:321:8)
    at Receiver.processPacket (C:\Users...\node_modules\ws\lib\Receiver.js:212:12)
    at Receiver.add (C:\Users...\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (C:\Users...\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

**Comment by hassanila** [comment]
@picusc You need to update to latest version, it's fixed already

**Comment by davidmann4** [comment]
try to reinstall 
npm install
