### ISSUE TITLE
Packet error detected for packet

### ISSUE THREAD

**Issue by zeliad-papa** [davidmann4/ogar-feeder-bot#237]
if i put many (4000) proxy i have error after 5-10min

```
Bot_406: New Cell Generated (2743086)
Bot_555: 2731027(a) has killed a cell.
Bot_555: Has been killed, respawning.
Bot_836: [warning] unknown packet ID(0): 00 46 00 55 00 43 00 4b 00 20 00 50 00 4c 00 45 00 53 00 54 00 49 00 4e 00 45 00
Bot_364: New Cell Generated (2743085)
Bot_648: Packet error detected for packet: 10 00 00 de 98 29 00 a1 f3 ff ff ed e4 ff ff 36 00 91 ff 07 00 00 00 e1 b0 29 00 38 ee ff ff 3a e9 ff ff 3f 00 07 68 ff 00 00 00 05 b2 29 00 a4 f0 ff ff 4f e9 ff ff 3d 00 ff 07 dc 00 00 00 a7 b4 29 00 d4 ef ff ff a4 e6 ff ff 43 00 07 ff e4 00 00 00 4b b6 29 00 88 f3 ff ff e8 e4 ff ff 30 00 4b ff 07 00 00 00 b5 ba 29 00 1c f0 ff ff 4b e7 ff e7 ff ff 22 00 fc 07 ff 00 00 00 dc d3 29 00 ee f2 ff ff e6 e6 ff ff 21 00 ff 07 ca 00 00 00 00 00 00 00 00 00 00 00 82 7e 00 c3 10 00 00 de 98 29 00 d0 f2 ff ff d3 e4 ff ff 36 00 91 ff 07 00 00 00 e1 b0 29 00 28 ee ff ff ed e8 ff ff 3f 00 07 68 ff 00 00 00 05 b2 29 00 f0 f0 ff ff 65 e9 ff ff 3d 00 ff 07 dc 00 00 00 a7 b4 29 00 72 ef ff ff a3 e6 ff
Bot_648: Crash will be prevented, bot will be disconnected
/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of reserved fields must be empty
    at WebSocket.onError (/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/home/agar/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/home/agar/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:195:12)
    at Receiver.add (/home/agar/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)

```

or

```
Bot_647: Packet error detected for packet: 10 5a 18 00 00 dd e9 ff ff 00 00 00 00
Bot_647: Crash will be prevented, bot will be disconnected
Bot_837: New Cell Generated (2787062)
/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^
TypeError: Cannot assign to read only property 'type' of reserved fields must be empty
    at WebSocket.onError (/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:426:16)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onerror (/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/home/agar/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/home/agar/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:195:12)
    at Receiver.add (/home/agar/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/home/agar/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:800:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
agar@YaiRapid:~/ogar-feeder-bot $
```

**Comment by ghost** [comment]
Go to node_modules>ws>lib>WebSocket.js>go to line 426 and 427 then just comment out by // in the front

**Comment by zeliad-papa** [comment]
thx
