### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by davidmann4** [davidmann4/ogar-feeder-bot#239]
/root/node_modules/socket.io/node_modules/engine.io/lib/socket.js:328
  if ('closed' != this.readyState && this.transport.writable
               ^
RangeError: Maximum call stack size exceeded
    at Socket.flush (/root/node_modules/socket.io/node_modules/engine.io/lib/socket.js:338:32)
    at WebSocket.emit (events.js:129:20)
    at /root/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:94:14
    at afterWrite (_stream_writable.js:361:3)
    at _stream_writable.js:349:9
    at process._tickCallback (node.js:355:11)

**Comment by ghost** [comment]
yeah I get those too :/

**Comment by ghost** [comment]
@Butterflypanda seems like theres alot of bugs

**Comment by hassanila** [comment]
@DavidMann4   http://stackoverflow.com/questions/20243945/nodejs-huge-array-processing-throws-rangeerror-maximum-call-stack-size-exceeded

SetImmediate()  should fix it....   check it out on stackoverflow
It's because a function gets called directly after one another and after sometime it goes into an endless loop... that's the cause of the error....

Read more at stackoverflow

---

![2016-02-24 08_18_30-javascript - nodejs huge array processing throws rangeerror_ maximum call stack](https://cloud.githubusercontent.com/assets/15068696/13278245/57936762-dacf-11e5-8ac9-5c9ea066b73e.png)
