### ISSUE TITLE
Cannot read property 'suicide_targets' of null

### ISSUE THREAD

**Issue by ruDeezle** [davidmann4/ogar-feeder-bot#293]
TypeError: Cannot read property 'suicide_targets' of null
    at Object.FeederBot.getCandidateBall (C:\Users\Deezle\Desktop\Deezle\feeder.
js:406:36)
    at Object.FeederBot.recalculateTarget (C:\Users\Deezle\Desktop\Deezle\feeder
.js:485:34)
    at null._repeat (C:\Users\Deezle\Desktop\Deezle\feeder.js:91:21)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

C:\Users\Deezle\Desktop\Deezle>Pause

**Comment by philw1508** [comment]
Yeaa.. New update caused it :(

**Comment by Petterholm** [comment]
If you want spam bots change it to default not blind mode

**Comment by Petterholm** [comment]
Sjould fix the problem

**Comment by MasonBurdette** [comment]
Mine still work..?

**Comment by philw1508** [comment]
@MasonBurdette can u send me yours? I have edited ogar feeder bot and bots arent Spawn Ing!

**Comment by philw1508** [comment]
*sorry I meant moving

**Comment by Petterholm** [comment]
He is not giving/selling to anyone because he used alot of time on them

Sendt fra min iPhone

**Comment by WJKH** [comment]
> He is not giving/selling to anyone because he used alot of time on them

Then he has some expiry time?
Do you mean if more people use it he will lost time or what?

**Comment by MasonBurdette** [comment]
I took the time to program a fix.  I don't want Ti to be patched.

**Comment by RudaGabriel** [comment]
default mod is working

**Comment by easyrider81** [comment]
@RudaGabriel working how? the bots don't come to you or have mouse control.
