### ISSUE TITLE
Bot stops after ~20 secs

### ISSUE THREAD

**Issue by ruDeezle** [davidmann4/ogar-feeder-bot#294]
```
Bot_3388: Connection Failed: Error: socket hang up
Bot_1051: Connection Failed: Error: socket hang up
Bot_1508: Disconnected from the server.
Bot_79: Disconnected from the server.
Bot_4152: Packet error detected for packet: 10 00 00 56 47 a3 bc 17 f4 ff ff e7
08 00 00 7f 00 07 ff fc 00 00 00 67 42 a3 bc 70 fb ff ff 06 03 00 00 68 03 07 8b
 ff 00 00 00 b8 77 a3 bc 05 f4 ff ff a8 07 00 00 bf 00 07 ff fc 00 00 00 8c 7c a
3 bc c6 f4 ff ff 05 05 00 00 59 00 17 ff 07 00 00 00 61 7a a3 bc 78 f5 ff ff cb
04 00 00 5c 00 07 8b ff 00 00 00 f3 66 a3 bc d1 f6 ff ff 47 07 00 00 13 01 07 ff
 6b 00 00 00 8c 6d a3 bc 63 f6 ff ff ce 08 00 00 94 00 07 23 ff 00 00 00 90 6d a
3 bc b9 f4 ff ff 8e 05 00 00 8e 05 00 00 25 00 07 23 ff 20 00 00 b8 6d a3 bc bc
f5 ff ff 20 04 00 00 25 00 07 8b ff 20 00 00 c6 6b a3 bc ec f6 ff ff ae 05 00 00
 3a 00 ff 07 fe 00 00 00 c9 6b a3 bc e0 f6 ff ff 3a 05 00 00 3a 00 ff 07 fe 00 0
0 00 00 00 00 00
Bot_4152: Crash will be prevented, bot will be disconnected
C:\Users\Deezle\Desktop\Deezle\node_modules\ws\lib\WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of continuation frame cann
ot follow current opcode
    at WebSocket.onError (C:\Users\Deezle\Desktop\Deezle\node_modules\ws\lib\Web
Socket.js:426:16)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onerror (C:\Users\Deezle\Desktop\Deezle\node_modules\ws\lib\WebS
ocket.js:851:10)
    at Receiver.error (C:\Users\Deezle\Desktop\Deezle\node_modules\ws\lib\Receiv
er.js:321:8)
    at Receiver.processPacket (C:\Users\Deezle\Desktop\Deezle\node_modules\ws\li
b\Receiver.js:212:12)
    at Receiver.add (C:\Users\Deezle\Desktop\Deezle\node_modules\ws\lib\Receiver
.js:95:24)
    at Socket.realHandler (C:\Users\Deezle\Desktop\Deezle\node_modules\ws\lib\We
bSocket.js:800:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)

C:\Users\Deezle\Desktop\Deezle>Pause

```

is it trouble with proxys? I have 2k proxys for DDOS, if ill use only working proxyes will it work without isuues?

**Comment by ruDeezle** [comment]
I need to DDOS servers with bots without restarting bots every 20 secs
