### ISSUE TITLE
Blind mode crash

### ISSUE THREAD

**Issue by G0ld3neyes** [davidmann4/ogar-feeder-bot#308]
When I use blind mode, ogar-feeder-bot gives me this crashlog:

C:\DATA\ogar-feeder-bot-master\feeder.js:406
                             if(valid_player_pos["suicide_targets"] == null){
                                                           ^

TypeError: Cannot read property 'suicide_targets' of null
  at Object.FeederBot.getCandidateBall (C:\DATA\ogar-feeder-bot-master\feeder.js:406:36)
  at Object.FeederBot.recalculateTarget (C:\DATA\ogar-feeder-bot-master\feeder.js:485:34)
  at null.repeat (C:\DATA\ogar-feeder-bot-master\feeder.js:91:21)
  at wrapper [as _onTimeout](timers.js:275:11)
  at Timer.listOnTimeout (timers.js:92:15)

Is there any way to fix this?

**Comment by santabis** [comment]
why you correct in ogar feeder?

**Comment by santabis** [comment]
panel ogar feeder Pached
delete panel

**Comment by G0ld3neyes** [comment]
@santabis what?
