### ISSUE TITLE
Please help i have a big error

### ISSUE THREAD

**Issue by tommyb008** [davidmann4/ogar-feeder-bot#309]
C:\Users\tommy\Desktop\Pemebots\feeder.js:406
                if(valid_player_pos["suicide_targets"] == null){
                                   ^

TypeError: Cannot read property 'suicide_targets' of null
    at Object.FeederBot.getCandidateBall (C:\Users\tommy\Desktop\Pemebots\feeder.js:406:36)
    at Object.FeederBot.recalculateTarget (C:\Users\tommy\Desktop\Pemebots\feeder.js:485:34)
    at null._repeat (C:\Users\tommy\Desktop\Pemebots\feeder.js:91:21)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

C:\Users\tommy\Desktop\Pemebots>pause
Press any key to continue . . .

please help

**Comment by G0ld3neyes** [comment]
Same thing,
This error only occurs when you have "config.botMode" set to "blind" in the config.js file.
I've tested it on windows and linux, both give me the same error.
I've also tested it on public and ogar servers, both give the same error.
Someone please help us out.

**Comment by tommyb008** [comment]
im curious does this let the bots follow you?

**Comment by Petterholm** [comment]
Agario has patched it!

**Comment by AppDeveloperMax** [comment]
Not patched i see a big mount of bots of diferents sites
