### ISSUE TITLE
feeder.js:201 TypeError: Cannot set property 'x' of null

### ISSUE THREAD

**Issue by zeliad-papa** [davidmann4/ogar-feeder-bot#32]
Last update have bug sometime:

```
        candidate_ball.x = valid_player_pos["x"];
                         ^
```

TypeError: Cannot set property 'x' of null
    at Object.FeederBot.recalculateTarget (/home/admin/agar/agario-feeder-bot/feeder.js:201:30)
    at null.<anonymous> (/home/admin/agar/agario-feeder-bot/feeder.js:63:58)
    at wrapper [as _onTimeout](timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by davidmann4** [comment]
newest version ? 

git pull

**Comment by zeliad-papa** [comment]
33 says: My new ball 60289
31 says: My new ball 60290
17 says: 59938(origin) ate my ball
17 says: Lost all my balls, respawning
17 says: My new ball 60291
34 says: Connecting to ws://104.236.100.252:443
/home/admin/agar/agario-feeder-bot/feeder.js:217
            bot.client.moveTo(valid_player_pos["x"], valid_player_pos["y"]);
                                              ^
TypeError: Cannot read property 'x' of null
    at Object.FeederBot.recalculateTarget (/home/admin/agar/agario-feeder-bot/feeder.js:217:47)
    at null.<anonymous> (/home/admin/agar/agario-feeder-bot/feeder.js:62:58)
    at wrapper [as _onTimeout](timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)
[admin@server agario-feeder-bot]$ git pull
Already up-to-date.

**Comment by davidmann4** [comment]
different error message 

caused by not having the userscript running in the browser
