### ISSUE TITLE
Cannot read property 'suicide_targets' of null

### ISSUE THREAD

**Issue by ghost** [davidmann4/ogar-feeder-bot#323]
**Error:**
C:\DATA\ogar-feeder-bot-master\feeder.js:406
                if(valid_player_pos["suicide_targets"] == null){
                                   ^

TypeError: Cannot read property 'suicide_targets' of null
    at Object.FeederBot.getCandidateBall (C:\DATA\ogar-feeder-bot-master\feeder.
js:406:36)
    at Object.FeederBot.recalculateTarget (C:\DATA\ogar-feeder-bot-master\feeder
.js:485:34)
    at null._repeat (C:\DATA\ogar-feeder-bot-master\feeder.js:91:21)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)****

**Comment by makandz** [comment]
I get the same error @davidmann4
