### ISSUE TITLE
Error in agario-client.js

### ISSUE THREAD

**Issue by ririmi56** [davidmann4/ogar-feeder-bot#324]
i have this issue after 10 secondes:

D:\Bureau\ogar-feeder-bot-master\node_modules\agario-client\agario-client.js:527
                throw e;
                ^

TypeError: Cannot read property 'name' of undefined
    at D:\Bureau\ogar-feeder-bot-master\feeder.js:133:49
    at Array.map (native)
    at Object.<anonymous> (D:\Bureau\ogar-feeder-bot-master\feeder.js:132:38)
    at Object.g (events.js:260:16)
    at emitMany (events.js:108:13)
    at Object.emit (events.js:182:7)
    at Object.Client.emitEvent (D:\Bureau\ogar-feeder-bot-master\node_modules\agario-client\agario-client.js:524:23)
    at Client.processors.49 (D:\Bureau\ogar-feeder-bot-master\node_modules\agario-client\agario-client.js:411:20)
    at Object.Client.onMessage (D:\Bureau\ogar-feeder-bot-master\node_modules\agario-client\agario-client.js:154:13)
    at WebSocket.onMessage (D:\Bureau\ogar-feeder-bot-master\node_modules\ws\lib\WebSocket.js:418:14)

**Comment by ghost** [comment]
same dude its a bug

**Comment by BreakAgar** [comment]
Update agario-client

**Comment by ItzLevvie** [comment]
@ririmi56 Update agario-client which can be installed via (```npm install agario-client```)

**Comment by ririmi56** [comment]
Same issue after "npm install agario-client"...
