### ISSUE TITLE
i got a problem

### ISSUE THREAD

**Issue by beaaan** [davidmann4/ogar-feeder-bot#352]
node server/server
Starting server on port 8081

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Object.<anonymous> (/home/trojan/ogar-feeder-bot/server/server.js:6:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
HOW TO FIX

**Comment by hassanila** [comment]
It says that port 8081 is in use.  Check that you're not running multiple servers and also that no program is using that port (8081) if the problem persists then just change the port to something else in config.js and also in the userscript.    If you don't understand then just restart your pc and it should be fixed.  :+1:
