### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by beaaan** [davidmann4/ogar-feeder-bot#361]
/home/trojan/BOTS/node_modules/agario-client/agario-client.js:528
                throw e;
                      ^
TypeError: Cannot read property 'name' of undefined
    at /home/trojan/BOTS/feeder.js:133:49
    at Array.map (native)
    at Object.<anonymous> (/home/trojan/BOTS/feeder.js:132:38)
    at Object.g (events.js:180:16)
    at Object.EventEmitter.emit (events.js:106:17)
    at Object.Client.emitEvent (/home/trojan/BOTS/node_modules/agario-client/agario-client.js:525:23)
    at Client.processors.49 (/home/trojan/BOTS/node_modules/agario-client/agario-client.js:411:20)
    at Object.Client.onMessage (/home/trojan/BOTS/node_modules/agario-client/agario-client.js:154:13)
    at WebSocket.onMessage (/home/trojan/BOTS/node_modules/agario-client/node_modules/ws/lib/WebSocket.js:418:14)
    at WebSocket.EventEmitter.emit (events.js:98:17)

**Comment by ElieeCh** [comment]
Go to your agario-client.js which is located in agario-client in the node_modules folder open it in notepad++ (Recommended) or sublime text than go to line 528 and edit the whole line to //throw e; (Also see the picture) 
![throw](https://cloud.githubusercontent.com/assets/18157373/14230546/05db69ae-f92b-11e5-8e8a-fa8ef0757e81.PNG)

If it doesn't work delete your agario-client and replace it with the new one https://github.com/pulviscriptor/agario-client 

If you have anymore questions about this issue post them here and if you don't please close the thread.

**Comment by beaaan** [comment]
tks for helping ^_^
