### ISSUE TITLE
Help!!!!

### ISSUE THREAD

**Issue by beaaan** [davidmann4/ogar-feeder-bot#384]
Bot_21: Packet error detected for packet: 10 00 00 97 93 35 79 5b ed ff ff 1d fa ff ff 28 00 07 ff e4 00 00 00 32 94 35 79 e7 f0 ff ff a7 fc ff ff 2d 00 3a ff 07 00 00 00 39 97 35 79 f9 eb ff ff 81 fe ff ff 26 00 07 ed ff 00 41 00 67 00 61 00 72 00 42 00 6f 00 63 01 73 00 2e 00 6e 00 65 00 74 00 00 00 57 97 35 79 f0 ee ff ff ef fc ff ff 20 00 07 57 ff 00 00 00 b9 88 35 79 00 ee ff ff 0e fc ff ff 24 00 ff 07 34 00 00 00 d7 8a 35 79 83 ef ff 00 3a ff 07 00 00 00 39 97 35 79 18 ec ff ff 77 fe ff ff 26 00 07 ed ff 00 00 00 57 97
Bot_21: Crash will be prevented, bot will be disconnected
/home/khanh/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:426
    event.type = 'error';
               ^

TypeError: Cannot assign to read only property 'type' of reserved fields must be empty
    at WebSocket.onError (/home/khanh/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (/home/khanh/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/home/khanh/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/home/khanh/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:195:12)
    at Receiver.add (/home/khanh/ogar-feeder-bot/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/home/khanh/ogar-feeder-bot/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

**Comment by VoOoLoX** [comment]
@bean07 I solved this by just commenting out everything inside onError function in
/node_modules/ws/lib/WebSocket.js

But this is very bad way of doing it

**Comment by hassanila** [comment]
VERY VERY BAD.      THE SOLUTION IS TO DELETE **node_modules** folder and reinstall dependencies via `npm install`
