### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Flathe** [davidmann4/ogar-feeder-bot#408]
Hey, 
I have some issues with the feeder.js : 

TypeError: Cannot read property 'name' of undefined
    at C:\Users****\Desktop\ogar-feeder-bot-master\ogar-feeder-bot-master\feede
r.js:133:49
    at Array.map (native)
    at Object.<anonymous> (C:\Users\Falt\Desktop\ogar-feeder-bot-master\ogar-fee
der-bot-master\feeder.js:132:38)
    at Object.g (events.js:260:16)
    at emitMany (events.js:108:13)
    at Object.emit (events.js:182:7)
    at Object.Client.emitEvent (C:\Users\Falt\Desktop\ogar-feeder-bot-master\oga
r-feeder-bot-master\node_modules\agario-client\agario-client.js:527:23)
    at Client.processors.49 (C:\Users\Falt\Desktop\ogar-feeder-bot-master\ogar-f
eeder-bot-master\node_modules\agario-client\agario-client.js:413:20)
    at Object.Client.onMessage (C:\Users\Falt\Desktop\ogar-feeder-bot-master\oga
r-feeder-bot-master\node_modules\agario-client\agario-client.js:156:13)
    at WebSocket.onMessage (C:\Users\Falt\Desktop\ogar-feeder-bot-master\ogar-fe
eder-bot-master\node_modules\ws\lib\WebSocket.js:442:14)

I tried to change 527th line in agario-client.js with //throw e; but all the bot try to connect and none work ... i updated agario-client but still nothing

Can someone can help me ?
Thanks

**Comment by meyerzinn** [comment]
Same issue. Just added a null check, now avoids the issue but the bots keep disconnecting.

**Comment by ghost** [comment]
fixed
