### ISSUE TITLE
Error running feeder.js Bots with VPS on Ubuntu ?

### ISSUE THREAD

**Issue by easyrider81** [davidmann4/ogar-feeder-bot#436]
Would it be possible for someone who knows more than myself to guide me through running the ogar feeder from my vps? I need to install node js on my vps right?

getting this error when running the feeder:

agario-feeder-bot started! Join a game in Chrome with the Userscript installed.
Press CTRL + C to stop this script.
/root/node_modules/ws/lib/WebSocket.js:392
      throw new SyntaxError('unsupported binaryType: must be either "nodebuffer" or "arraybuffer"');
      ^

SyntaxError: unsupported binaryType: must be either "nodebuffer" or "arraybuffer"
    at WebSocket.set (/root/node_modules/ws/lib/WebSocket.js:392:13)
    at WS.doOpen (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/transports/websocket.js:108:24)
    at WS.Transport.open (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:78:10)
    at Socket.probe (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:382:13)
    at Socket.onOpen (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:404:12)
    at Socket.onHandshake (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:464:8)
    at Socket.onPacket (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:426:14)
    at XHR.<anonymous> (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/socket.js:258:10)
    at XHR.Emitter.emit (/root/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/component-emitter/index.js:134:20)
    at XHR.Transport.onPacket (/root/node_modules/socket.io-client/node_modules/engine.io-client/lib/transport.js:143:8)

anyone know what i need to do?

**Comment by easyrider81** [comment]
sorted myself

**Comment by zhirzh** [comment]
can you please post how you solved the issue?

I am facing the same problem right now and can't fix it

**Comment by CalvinDKL** [comment]
PLS POST FIX!
