### ISSUE TITLE
port 8081 windows server 2012

### ISSUE THREAD

**Issue by dimamelnic** [davidmann4/ogar-feeder-bot#452]
I have 2 windows server 2012
1 works well about 150 bot can run
2 does not work, and wrote at the end of
All FBs Successfully Checked ..
ogar-feeder-bot started! Join a game in Chrome with the Userscript installed.
Press CTRL + C to stop this script.
startup
server-booted-up

help me please. Can anyone help. betray windose 1 server

antivirus disabled

**Comment by ghost** [comment]
Use c9.io or put "ws://bots.myservers.io:8081" in userscript and config.js

**Comment by SanjaySasimandir** [comment]
Try using good proxies. most of the time bad proxies cause the problem. I use proxybag.blogspot.com
They lots good proxies, 25% of proxies work. Hope that helps you.

**Comment by Martinali12** [comment]
check ur uidu lol

**Comment by dimamelnic** [comment]
@nfsboy101 I wrote. I have 2 private server windose Server 2012
1 operates and the proxy all identical and the second is the same.

**Comment by dimamelnic** [comment]
@Martinali12 I wrote. I have 2 private server windose Server 2012
1 operates and the proxy all identical and the second is the same.

**Comment by Qasimmodo** [comment]
Set your Userscript and your server-sided files (config.js) to ws://bots.myservers.io:8081 Just search for ws:// in Notepad or in TamperMonkey and you'll find it in config.js and the userscript.

**Comment by GoCyb3r** [comment]
@Qasimmodo I did it, but still it can't connect to the server

**Comment by GoCyb3r** [comment]
After I manually started the server.js : 

events.js:141  
      throw er; // Unhandled 'error' event  
      ^                                                                                                      

Error: read ECONNRESET  
    at exports._errnoException (util.js:870:11)  
    at TCP.onread (net.js:550:26)                                                                            

Process exited with code: 1
