### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by Kasra-G** [davidmann4/ogar-feeder-bot#477]
Is it normal for the bot console to get spammed with failed tokens and then:

SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users(USER)\Desktop\FreeAgarBotsFB\Bots\a\f.js:28:13
    at new Account Validated (C:\Users(USER)\Desktop\FreeAgarBotsFB\Bots\a\facebookManager.js:9326:17)
    at C:\Users(USER)\Desktop\FreeAgarBotsFB\Bots\a\facebookManager.js:9315:13

C:\Users(USER)\Desktop\FreeAgarBotsFB\Bots\a>pause

I switched out the user's name with (USER)

Nice work with the code btw, was it just you 2 or a whole team?

**Comment by ghost** [comment]
You write correct, the cookies?

**Comment by Kasra-G** [comment]
I don't understand D:

I went and snooped around in the files and  found a place where it said to input facebook credentials

(xs, datr, c_user) and I did it, but it did not fix the issue

**Comment by Kasra-G** [comment]
nevermind, i managed to fix it somehow :/. Just messed around with a bunch of files and it got fixed
