### ISSUE TITLE
Help Me please !!!

### ISSUE THREAD

**Issue by AdibAgar** [davidmann4/ogar-feeder-bot#528]
When I install :( 
https://www.youtube.com/watch?v=ZzJJAB79TgI
# I get this

**module.js:341
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Adib\Desktop\Ogar-unlimited-master\node_modu
les\request\node_modules\readable-stream\lib_stream_duplex.js:21:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...**

**Comment by sejo153** [comment]
I think you just need to add [THIS](https://github.com/calvinmetcalf/process-nextick-args) in your node modules whic is missing

**Comment by AdibAgar** [comment]
@sejo153 in which file ?

**Comment by sejo153** [comment]
try in src-modules

**Comment by AdibAgar** [comment]
now i get
Error: Cannot find module 'isarray'

**Comment by sejo153** [comment]
just google like "issaray github"
and download it and put in module folder
And whatever it wants download it

**Comment by AdibAgar** [comment]
@sejo153  Thnx Bro :) 
i really want to try that Private server :p

**Comment by Nick8fr32** [comment]
U can also just type npm install isarray

**Comment by ghost** [comment]
close the issue if solved
