### ISSUE TITLE
help installing

### ISSUE THREAD

**Issue by Octolus** [davidmann4/ogar-feeder-bot#85]
[root@agar agario-feeder-bot-master]# npm install package.json
npm ERR! not a package /root/tmp/npm-30196/1453936539021-0.8106397073715925/tmp.tgz
npm http GET https://registry.npmjs.org/package.json
npm http 304 https://registry.npmjs.org/package.json
package.json@0.0.0 node_modules/package.json

[root@agar agario-feeder-bot-master]# node feeder.js

/root/agario-feeder-bot-master/feeder.js:198
        return {x,y};
                 ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by Octolus** [comment]
i don't understand what i should edit in config.js, or "all" the packages i should install, pretty badly explained if you ask me

**Comment by davidmann4** [comment]
pretty basic stuff you can find with google

npm install package.json

shgould do the trick

**Comment by Octolus** [comment]
already installed

still

[root@agar agario-feeder-bot-master]# node feed.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/agario-feeder-bot-master/feed.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by davidmann4** [comment]
node feeder.js

**Comment by Octolus** [comment]
/root/agario-feeder-bot-master/feeder.js:198
        return {x,y};
                 ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by Octolus** [comment]
agario-feeder-bot.user.js  config.js  feeder.js  LICENSE  names.js  node_modules  package.json  proxy.txt  README.md  server
[root@agar agario-feeder-bot-master]# cd node_modules
[root@agar node_modules]# ls
express  package.json

**Comment by davidmann4** [comment]
take the newest version I changed the code

**Comment by Octolus** [comment]
Ok.

[root@agar agario-feeder-bot-master]# node feeder.js

/root/agario-feeder-bot-master/feeder.js:198
        return {x,y};
                 ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by Octolus** [comment]
do you have skype? i can pay 2 help

**Comment by davidmann4** [comment]
tomorrow

**Comment by Octolus** [comment]
ok i added you, i'll give ssh if you want to look

**Comment by Petterholm** [comment]
Update node to 5.50

**Comment by Petterholm** [comment]
That should fix it

**Comment by Octolus** [comment]
[root@agar agario-feeder-bot-master]# node -v
v5.4.1

thats what it updated to

**Comment by dragonpiper** [comment]
I have both scripts loaded but the most feeder logs is 
the following am i missing something ?

agario-feeder-bot started! Join a game in Chrome with the Userscript installed.
startup
server-booted-up

**Comment by Octolus** [comment]
still no luck, you should make a better tutorial ._.
